In [1]:
import pandas as pd

In [58]:
df = pd.DataFrame(columns=["Model", "Capacity (mAh)", "Cells", "Discharge Rate", "Volume (mm^3)", "Weight (g)"])
df

Empty DataFrame
Columns: [Model, Capacity (mAh), Cells, Discharge Rate, Volume (mm^3), Weight (g)]
Index: []

In [59]:
df = pd.DataFrame({"Model":["Turnigy Nano-Tech"],
           "Capacity (mAh)":[5000],
           "Cells":[3],
           "Discharge Rate":[25],
           "Volume (mm^3)":[337218],
           "Weight (g)":[490.8]})
df

,Capacity (mAh),Cells,Discharge Rate,Model,Volume (mm^3),Weight (g)
0,5000,3,25,Turnigy Nano-Tech,337218,490.8

In [60]:
aux = pd.DataFrame({"Model":["FayOK"],
           "Capacity (mAh)":[8000],
           "Cells":[3],
           "Discharge Rate":[40],
           "Volume (mm^3)":[262080],
           "Weight (g)":[595]})
df = df.append(aux)
df

,Capacity (mAh),Cells,Discharge Rate,Model,Volume (mm^3),Weight (g)
0,5000,3,25,Turnigy Nano-Tech,337218,490.8
0,8000,3,40,FayOK,262080,595.0

In [62]:
aux = pd.DataFrame({"Model":["YOWOO Graphene Battery"],
           "Capacity (mAh)":[5000],
           "Cells":[3],
           "Discharge Rate":[100],
           "Volume (mm^3)":[171120],
           "Weight (g)":[451.5]})
df = df.append(aux)
aux = pd.DataFrame({"Model":["ZIPPY Flightmax"],
           "Capacity (mAh)":[5000],
           "Cells":[3],
           "Discharge Rate":[20],
           "Volume (mm^3)":[188500],
           "Weight (g)":[404]})
df = df.append(aux)

/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

In [67]:
df["Volumetric Density"] = df["Capacity (mAh)"]/df["Volume (mm^3)"]
df["Weight-Charge Density"] = df["Capacity (mAh)"]/df["Weight (g)"]
df

,Capacity (mAh),Cells,Discharge Rate,Model,Volume (mm^3),Volumetric Density,Weight (g),Weight-Charge Density
0,8000,3,40,FayOK,262080,0.030525,595.0,13.445378
0,5000,3,100,YOWOO Graphene Battery,171120,0.029219,451.5,11.074197
0,5000,3,20,ZIPPY Flightmax,188500,0.026525,404.0,12.376238
0,5000,3,25,Turnigy Nano-Tech,337218,0.014827,490.8,10.187449

In [68]:
df.sort_values(["Volumetric Density"], ascending=False)

,Capacity (mAh),Cells,Discharge Rate,Model,Volume (mm^3),Volumetric Density,Weight (g),Weight-Charge Density
0,8000,3,40,FayOK,262080,0.030525,595.0,13.445378
0,5000,3,100,YOWOO Graphene Battery,171120,0.029219,451.5,11.074197
0,5000,3,20,ZIPPY Flightmax,188500,0.026525,404.0,12.376238
0,5000,3,25,Turnigy Nano-Tech,337218,0.014827,490.8,10.187449